---
- name: Add custom scripts to the plugin dir
  copy:
    src: files/scripts/
    dest: /usr/libexec/icinga2/
    group: icinga
    owner: icinga
    mode: 0755
    force: yes
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

- name: Add custom scripts to the plugin dir
  copy:
    src: files/scripts/
    dest: /usr/libexec/icinga2/
    group: user
    owner: user
    mode: 0755
    force: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
