---
- name: Add IC2 dir for systemd override
  file:
    path: /etc/systemd/system/icinga2.service.d
    state: directory

- name: Add override file
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/icinga2.service.d/override.conf

- name: Reload systemd daemons and restart daemon
  systemd:
    name: icinga2.service
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"
  ignore_errors: yes

- name: Restart daemon
  service:
    name: icinga2
    state: restarted
    enabled: yes
  when: ansible_service_mgr != "systemd"
  ignore_errors: yes
