---
- name: Install snmpd
  apt:
    name: snmpd
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version > "16" 

- name: Move SNMPD conf file
  copy:
    src: /home/user/snmpd.conf
    dest: /etc/snmp/
    owner: root
    group: root
    mode: 0600
#  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version > "16"

- name: Stop snmpd
  service:
    name: snmpd
    state: stopped

- name: Setup snmpv3 user
  command: net-snmp-create-v3-user -ro -a MD5 -x DES -X
  ignore_errors: yes

- name: Start and Enable snmpd
  service:
    name: snmpd
    state: started
    enabled: yes
